### ISSUE TITLE
Number of devices 1 must equal the product of mesh_shape (1, 8)？

### ISSUE THREAD

**Issue by vjsplus** [xai-org/grok-1#198] opened 2024-03-19 10:17 UTC
Maybe it's a stupid question. What equipment do you need?

```
grok-1 % python run.py
INFO:jax._src.xla_bridge:Unable to initialize backend 'cuda': 
INFO:jax._src.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
INFO:jax._src.xla_bridge:Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: dlopen(libtpu.so, 0x0001): tried: 'libtpu.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibtpu.so' (no such file), '/opt/anaconda3/bin/../lib/libtpu.so' (no such file), '/usr/lib/libtpu.so' (no such file, not in dyld cache), 'libtpu.so' (no such file), '/usr/local/lib/libtpu.so' (no such file), '/usr/lib/libtpu.so' (no such file, not in dyld cache)
INFO:rank:Initializing mesh for self.local_mesh_config=(1, 8) self.between_hosts_config=(1, 1)...
INFO:rank:Detected 1 devices in mesh
Traceback (most recent call last):
  File "/Users/vjs/grok-1/run.py", line 72, in <module>
    main()
  File "/Users/vjs/grok-1/run.py", line 63, in main
    inference_runner.initialize()
  File "/Users/vjs/grok-1/runners.py", line 282, in initialize
    runner.initialize(
  File "/Users/vjs/grok-1/runners.py", line 181, in initialize
    self.mesh = make_mesh(self.local_mesh_config, self.between_hosts_config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vjs/grok-1/runners.py", line 586, in make_mesh
    device_mesh = mesh_utils.create_hybrid_device_mesh(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/jax/experimental/mesh_utils.py", line 373, in create_hybrid_device_mesh
    per_granule_meshes = [create_device_mesh(mesh_shape, granule)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/jax/experimental/mesh_utils.py", line 373, in <listcomp>
    per_granule_meshes = [create_device_mesh(mesh_shape, granule)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/jax/experimental/mesh_utils.py", line 302, in create_device_mesh
    raise ValueError(f'Number of devices {len(devices)} must equal the product '
ValueError: Number of devices 1 must equal the product of mesh_shape (1, 8)
```

**Comment by bluevisor** [comment] 2024-03-19 11:08
https://github.com/xai-org/grok-1/issues/38#issuecomment-2003933119

**Comment by trholding** [comment] 2024-03-19 12:22
8 GPUs are required with total VRAM that can fit the model.

Please see: https://github.com/xai-org/grok-1/discussions/183

Please close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Duplicate of / Related to:
#38 

Reason:
User's shell issue / Not a real issue
#69 
#108

**Closed** 2024-03-19 15:16 UTC
