### ISSUE TITLE
ERROR: No matching distribution found for jaxlib==0.4.25+cuda12.cudnn89; extra == "cuda12_pip"

### ISSUE THREAD

**Issue by cetindogu** [xai-org/grok-1#199] opened 2024-03-19 10:36 UTC
windows 11

"pip install -r requirements.txt"  fails

PS F:\grok-1> pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting dm_haiku==0.0.12 (from -r requirements.txt (line 1))
  Using cached dm_haiku-0.0.12-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: jax==0.4.25 in c:\users\cetin.dogu\appdata\roaming\python\python310\site-packages (from jax[cuda12_pip]==0.4.25->-r requirements.txt (line 2)) (0.4.25)
Requirement already satisfied: numpy==1.26.4 in c:\users\cetin.dogu\appdata\roaming\python\python310\site-packages (from -r requirements.txt (line 3)) (1.26.4)
Collecting sentencepiece==0.2.0 (from -r requirements.txt (line 4))
  Using cached sentencepiece-0.2.0-cp310-cp310-win_amd64.whl.metadata (8.3 kB)
Collecting absl-py>=0.7.1 (from dm_haiku==0.0.12->-r requirements.txt (line 1))
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting jmp>=0.0.2 (from dm_haiku==0.0.12->-r requirements.txt (line 1))
  Using cached jmp-0.0.4-py3-none-any.whl.metadata (8.9 kB)
Collecting tabulate>=0.8.9 (from dm_haiku==0.0.12->-r requirements.txt (line 1))
  Using cached tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Collecting flax>=0.7.1 (from dm_haiku==0.0.12->-r requirements.txt (line 1))
  Using cached flax-0.8.2-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: ml-dtypes>=0.2.0 in c:\users\cetin.dogu\appdata\roaming\python\python310\site-packages (from jax==0.4.25->jax[cuda12_pip]==0.4.25->-r requirements.txt (line 2)) (0.3.2)
Requirement already satisfied: opt-einsum in c:\users\cetin.dogu\appdata\roaming\python\python310\site-packages (from jax==0.4.25->jax[cuda12_pip]==0.4.25->-r requirements.txt (line 2)) (3.3.0)
Requirement already satisfied: scipy>=1.9 in c:\users\cetin.dogu\appdata\roaming\python\python310\site-packages (from jax==0.4.25->jax[cuda12_pip]==0.4.25->-r requirements.txt (line 2)) (1.12.0)
WARNING: jax 0.4.25 does not provide the extra 'cuda12-pip'
INFO: pip is looking at multiple versions of jax[cuda12-pip] to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement jaxlib==0.4.25+cuda12.cudnn89; extra == "cuda12_pip" (from jax[cuda12-pip]) (from versions: 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.24, 0.4.25)
ERROR: No matching distribution found for jaxlib==0.4.25+cuda12.cudnn89; extra == "cuda12_pip"
PS F:\grok-1>

**Comment by cetindogu** [comment] 2024-03-19 10:38
PS F:\grok-1> pip list
Package            Version
------------------ --------
certifi            2024.2.2
charset-normalizer 3.3.2
colorama           0.4.6
filelock           3.13.1
fsspec             2024.3.1
hf_transfer        0.1.6
huggingface-hub    0.21.4
idna               3.6
jax                0.4.25
ml-dtypes          0.3.2
numpy              1.26.4
opt-einsum         3.3.0
packaging          24.0
pip                24.0
PyYAML             6.0.1
requests           2.31.0
scipy              1.12.0
setuptools         63.2.0
tqdm               4.66.2
typing_extensions  4.10.0
urllib3            2.2.1
wheel              0.43.0

**Comment by trholding** [comment] 2024-03-19 12:08
Please see: 

https://github.com/xai-org/grok-1/issues/186#issuecomment-2005883995

Please close this issue and instead comment to issue #6 which is open:

Related to / Duplicate of:
https://github.com/xai-org/grok-1/issues/173
https://github.com/xai-org/grok-1/issues/143
https://github.com/xai-org/grok-1/issues/106
https://github.com/xai-org/grok-1/issues/104
https://github.com/xai-org/grok-1/issues/102
https://github.com/xai-org/grok-1/issues/83
https://github.com/xai-org/grok-1/issues/82
https://github.com/xai-org/grok-1/issues/24
https://github.com/xai-org/grok-1/issues/6

Reason:
Duplicate
https://github.com/xai-org/grok-1/issues/69
https://github.com/xai-org/grok-1/issues/108

**Closed** 2024-03-19 15:16 UTC
