### ISSUE TITLE
What are the minimum hardware requirements for testing this code

### ISSUE THREAD

**Issue by chenzhipenga** [xai-org/grok-1#86] opened 2024-03-18 07:23 UTC
What are the minimum hardware requirements for testing this code

**Comment by Konard** [comment] 2024-03-18 07:35
I have already asked that question at https://github.com/xai-org/grok-1/issues/62

**Comment by xuzeyu91** [comment] 2024-03-18 07:42
According to rumors, we need 8 H100

**Comment by trholding** [comment] 2024-03-18 12:01
Please close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Reason:
#69 
#108 

Also duplicate of #62

**Closed** 2024-03-18 14:34 UTC
